# デフォルト設定（docker-compose の env で上書き）
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mariadb://db:3306/sampledb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:appuser}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:apppass}

# サーバポート
server.port=8080