# frontend/Dockerfile
FROM mcr.microsoft.com/devcontainers/java:21-bullseye

# 必要に応じてMavenやGradleのバージョンを指定（デフォルトでも入っています）
ARG MAVEN_VERSION=""
ARG GRADLE_VERSION=""

# [任意] OSのパッケージを追加する場合
RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
    && apt-get -y install --no-install-recommends curl git

# 作業ディレクトリの設定
WORKDIR /workspaces/frontend

# ポートの公開（Java Spring Bootなどのデフォルト 8080）
EXPOSE 8080