version: "3.3"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: sample-backend
    restart: unless-stopped
    environment:
      - AZURE_DOC_INTEL_ENDPOINT=${AZURE_DOC_INTEL_ENDPOINT}
      - AZURE_DOC_INTEL_KEY=${AZURE_DOC_INTEL_KEY}
    ports:
      - "5000:5000"
    networks:
      - sample-network


  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: sample-frontend
    restart: unless-stopped
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://${DB_HOST}:${DB_PORT}/${DB_NAME}?useSsl=true
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - BACKEND_API_URL=http://backend:5000/api
      - APP_STORAGE_S3_BUCKET=${S3_BUCKET}
      - APP_STORAGE_S3_REGION=${AWS_REGION}
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WEB=DEBUG
    ports:
      - "8080:8080"
    networks:
      - sample-network
    volumes:
      # 左側がWSL2(NAS)のパス、右側がコンテナ(Spring Boot)内のパス
      - /mnt/nas/hams_uploads:/app/uploads
      - ${HOME}/.aws:/root/.aws:ro

volumes:
  db-data:

networks:
  sample-network:
    driver: bridge